"""Immediate response action plan and a draft pollution report (POLREP).

Actions are generated by transparent rules from the analysis evidence and are aligned with the roles in India's
National Oil Spill Disaster Contingency Plan (NOS-DCP): the Indian Coast Guard is the Central Coordinating
Authority for marine oil spills; ports, coastal states/UTs and DG Shipping have supporting roles. They are
DECISION-SUPPORT SUGGESTIONS — the Coast Guard's on-scene commander decides. The POLREP is a draft for a human
to review and send; the system never sends messages."""
from __future__ import annotations

from datetime import datetime, timedelta

from app.impact.gazetteer import mrcc_for

P_ORDER = {"P1": 0, "P2": 1, "P3": 2}


def _dm(v: float, pos: str, neg: str, width: int) -> str:
    h = pos if v >= 0 else neg
    v = abs(v)
    d = int(v)
    return f"{d:0{width}d}°{(v - d) * 60:04.1f}'{h}"


def fmt_pos(lon: float, lat: float) -> str:
    """Nautical position, e.g. 18°54.0'N 072°30.0'E."""
    return f"{_dm(lat, 'N', 'S', 2)} {_dm(lon, 'E', 'W', 3)}"


def _hrs(h: float | None) -> str:
    if h is None:
        return "—"
    return f"{h:.0f} h" if h < 72 else f"{h / 24:.1f} days"


def action_plan(spill: dict, drift: dict | None, forward: dict | None, threat: dict, sev: dict, candidates: list[dict],
                intercepts: dict, cand_doc: dict | None, synthetic: dict) -> dict:
    c = spill["centroid"]
    mrcc = mrcc_for(c["lon"], c["lat"])
    obs = datetime.fromisoformat(spill["timestamp"])
    wind = ((drift or {}).get("forcing_at_spill") or {}).get("wind_speed")
    b = threat["beaching"]
    eta_b = b.get("eta_hours")
    thr = [s for s in threat["sites"] if s["threatened"]]
    acts: list[dict] = []

    def add(pri, deadline_h, agency, title, detail, why, kind):
        acts.append({"priority": pri, "deadline_hours": deadline_h,
                     "deadline_time": (obs + timedelta(hours=deadline_h)).isoformat() if deadline_h is not None else None,
                     "agency": agency, "title": title, "detail": detail, "why": why, "kind": kind})

    lvl = sev["level"]
    add("P1", 1, f"Indian Coast Guard — {mrcc['name']}", f"Report the detection to {mrcc['name']}",
        "Send the POLREP draft (below) to the MRCC / ICG pollution response cell and the port authority nearest the slick.",
        f"SSII {sev['score']:.0f} ({lvl}); {mrcc['region']}", "notify")
    add("P1", 3, "Indian Coast Guard (aerial / surface unit)", "Confirm the slick on scene",
        "Task a surveillance aircraft or the nearest ICG/port vessel to the forecast position "
        f"{fmt_pos(*(forward['end_center']['lon'], forward['end_center']['lat']))} to verify oil, appearance code and extent."
        if forward and forward.get("available") else "Task a surveillance aircraft or nearest vessel to the slick position.",
        "Satellite SAR detections require visual confirmation (look-alikes, thickness unknown).", "verify")
    add("P1", 6, "Indian Coast Guard / pollution response team", "Collect oil samples for fingerprinting",
        "Sample the slick (chain-of-custody forms) so it can be matched by GC-MS fingerprinting against samples from suspect vessels.",
        "Physical evidence is required to link a vessel to the spill.", "evidence")

    # shoreline / receptor protection, most urgent first
    for s in sorted(thr, key=lambda s: s["eta_hours"])[:5]:
        lead = max(s["eta_hours"] - 6, 1)
        pri = "P1" if s["eta_hours"] <= 24 else "P2" if s["eta_hours"] <= 72 else "P3"
        if s["type"] == "intake":
            title, agency = f"Alert {s['name']} to protect intakes", "Plant operator / NPCIL · ICG"
            detail = "Deploy intake booms / screens and prepare for load reduction if oil approaches the cooling-water intake."
        elif s["type"] in ("port",):
            title, agency = f"Prepare port-entrance protection at {s['name']}", "Port authority (Tier 1 resources) · ICG"
            detail = "Stage booms at the harbour entrance and berths; advise vessel traffic service (VTS)."
        elif s["type"] in ("fishing", "tourism"):
            title, agency = f"Issue advisory for {s['name']}", "State fisheries / tourism department · District administration"
            detail = "Advise fishing boats and beach users; pre-position shoreline clean-up teams."
        else:
            title, agency = f"Protect {s['name']} ({s['type_label']})", "State Forest / Environment dept · ICG · State Pollution Control Board"
            detail = "Deploy protective (exclusion / deflection) booms across inlets and creek mouths; avoid dispersants nearby."
        add(pri, lead, agency, title, detail + f" Forecast impact ~{_hrs(s['eta_hours'])} after observation.",
            f"{s['reason']}; receptor sensitivity {s['weight']}/10 ({s['receptor']})", "protect")

    if eta_b is not None and not thr:
        add("P1" if eta_b <= 24 else "P2", max(eta_b - 6, 1), "Coastal State/UT · District administration",
            f"Prepare shoreline response near {b['landing_place']}",
            "Pre-position shoreline clean-up resources and warn local communities.",
            f"Oil forecast to reach the shore in ~{_hrs(eta_b)} ({b['method'].replace('_', ' ')})", "protect")

    # at-sea response
    if wind is not None and wind > 10:
        add("P2", 6, "Indian Coast Guard", "Defer boom containment; monitor",
            f"Wind {wind:.1f} m/s exceeds typical boom operating limits — prioritise monitoring and shoreline protection.",
            "Containment booms lose effectiveness in strong wind / steep seas.", "contain")
    else:
        add("P1" if lvl in ("HIGH", "CRITICAL") else "P2", 6, "Indian Coast Guard (Pollution Response vessel)",
            "Contain and recover at sea",
            "Deploy containment booms and skimmers at the leading edge of the slick; recovered oil to port reception facility.",
            f"Wind {wind:.1f} m/s — within typical operating limits for booms." if wind is not None else "Wind unknown.", "contain")
    d_coast = threat.get("distance_to_coast_km")
    near_sens = any(s["distance_now_km"] < 30 for s in threat["sites"] if s["weight"] >= 8)
    if d_coast is not None and d_coast > 20 and not near_sens:
        add("P3", 12, "Indian Coast Guard (approval authority)", "Consider dispersants only with approval",
            "Dispersant use may be evaluated because the slick is offshore and away from sensitive receptors — requires ICG "
            "approval under the NOS-DCP dispersant policy and a check of oil type / weathering.",
            f"{d_coast:.0f} km offshore; no highly sensitive site within 30 km", "contain")
    else:
        add("P2", 6, "Indian Coast Guard", "Do not use dispersants here",
            "Rely on mechanical recovery and shoreline protection.",
            "Slick is near the coast or near highly sensitive receptors.", "contain")

    # enforcement
    for cd in candidates[:3]:
        v = cd["vessel"]
        ic = intercepts.get(v["mmsi"]) or {}
        where = (f"at {ic['port']} (ETA ~{_hrs(ic.get('eta_hours_from_last_fix'))} from last AIS fix)" if ic.get("port")
                 else f"(no Indian port ahead; nearest: {ic.get('nearest_port', 'n/a')})")
        pri = "P1" if cd["rank"] == 1 and cd["score"] >= 60 else "P2"
        add(pri, 24, "DG Shipping (Port State Control) · ICG", f"Inspect {v.get('name') or v['mmsi']} {where}",
            "Check the Oil Record Book (MARPOL Annex I), oily-water separator and 15 ppm alarm records; take bunker / cargo / "
            "bilge samples for fingerprint comparison." + (f" {ic['ais_silence']}." if ic.get("ais_silence") else ""),
            f"Candidate #{cd['rank']}, Evidence Correlation Score {cd['score']:.0f}"
            + (" — SYNTHETIC vessel (demonstration)" if cd.get("synthetic") else ""), "enforce")
    mm = (cand_doc or {}).get("sar_ais_mismatch") or {}
    n_dark = len(mm.get("sar_detections_without_ais", []) or [])
    if n_dark:
        add("P2", 12, "Indian Coast Guard / Navy (MDA)", f"Identify {n_dark} SAR-only vessel(s) without AIS",
            "Cross-check the SAR point targets near the slick with coastal radar / LRIT; unidentified ('dark') vessels are leads.",
            "Vessels switching off AIS are a known behaviour during illegal discharges.", "enforce")
    add("P2", 12, "INCOIS / ICG", "Update the forecast with the next satellite pass",
        "Request the next Sentinel-1 acquisition and re-run the forward forecast every 6 h with updated currents and wind.",
        "Drift forecasts degrade with time; new observations reset the uncertainty.", "monitor")
    if sev["response_tier"]["central"] != "Tier 1":
        add("P1", 2, "Indian Coast Guard (Central Coordinating Authority)", f"Activate {sev['response_tier']['central']} response",
            "Mobilise regional / national resources per NOS-DCP.", sev["response_tier"]["basis"], "notify")
    acts.sort(key=lambda a: (P_ORDER[a["priority"]], a["deadline_hours"] if a["deadline_hours"] is not None else 1e9))
    for i, a in enumerate(acts, 1):
        a["id"] = i
    notes = ["Decision-support suggestions aligned with NOS-DCP roles; the ICG on-scene commander decides."]
    if any(synthetic.values()):
        notes.append("Some inputs are SYNTHETIC (" + ", ".join(k for k, v in synthetic.items() if v) +
                     ") — this plan demonstrates the method and must not be acted upon.")
    return {"mrcc": mrcc, "actions": acts[:14], "notes": notes}


def polrep(spill: dict, drift: dict | None, forward: dict | None, threat: dict, sev: dict, candidates: list[dict],
           plan: dict, provenance: dict, synthetic: dict) -> str:
    c = spill["centroid"]
    obs = datetime.fromisoformat(spill["timestamp"])
    f = (drift or {}).get("forcing_at_spill") or {}
    b = threat["beaching"]
    syn = any(synthetic.values())
    L = ["POLREP — DRAFT FOR REVIEW (NOT SENT)" + ("  ***EXERCISE / SYNTHETIC DATA***" if syn else ""),
         f"TO: {plan['mrcc']['name']} ({plan['mrcc']['region']}) / ICG Pollution Response",
         "FROM: SIH26143 oil-spill investigation decision-support system",
         "PART I — POLWARN",
         f"1. DATE/TIME OF OBSERVATION: {obs:%d%H%MZ %b %Y}".upper(),
         f"2. POSITION (centroid): {fmt_pos(c['lon'], c['lat'])}",
         f"3. INCIDENT: oil slick detected by satellite SAR ({provenance.get('sar_image', 'SAR')})",
         f"4. EXTENT: area {spill['area_m2'] / 1e6:.2f} km²; estimated volume "
         f"{sev['volume_estimate']['m3']['low']:.1f}–{sev['volume_estimate']['m3']['high']:.0f} m³ (thickness assumed; unverified)",
         f"5. POSSIBLE SOURCE (under investigation, not established): " +
         ("; ".join(f"{x['vessel'].get('name') or x['vessel']['mmsi']} MMSI {x['vessel']['mmsi']} (score {x['score']:.0f})"
                    for x in candidates[:3]) or "no candidate identified"),
         f"6. WIND/CURRENT AT SLICK: wind {f.get('wind_speed', float('nan')):.1f} m/s from {f.get('wind_from_deg', float('nan')):.0f}°, "
         f"current {f.get('current_speed', float('nan')):.2f} m/s toward {f.get('current_to_deg', float('nan')):.0f}°",
         "PART II — POLINF",
         f"7. FORECAST: " + (f"centre after {forward['hours']:.0f} h at {fmt_pos(forward['end_center']['lon'], forward['end_center']['lat'])}"
                            if forward and forward.get("available") else "forward forecast unavailable"),
         "8. SHORELINE THREAT: " + (f"~{_hrs(b['eta_hours'])} to {b['landing_place']} ({b['method'].replace('_', ' ')})"
                                    if b.get("eta_hours") is not None else "none expected on current drift")
         + (f"; nearest shore {threat['distance_to_coast_km']:.1f} km" if threat.get("distance_to_coast_km") is not None else ""),
         "9. THREATENED RESOURCES: " + (", ".join(f"{s['name']} (~{_hrs(s['eta_hours'])})" for s in threat["sites"] if s["threatened"])
                                        or "none identified"),
         f"10. SEVERITY: SSII {sev['score']:.0f}/100 ({sev['level']}); planning estimate {sev['response_tier']['central']}",
         "PART III — POLFAC (requested actions)"]
    for a in [a for a in plan["actions"] if a["priority"] == "P1"][:6]:
        L.append(f"- [{a['priority']}] {a['title']} — {a['agency']}")
    L += [f"DATA: SAR {provenance.get('sar_image')}; forcing {provenance.get('environmental_forcing')}; AIS {provenance.get('ais')}",
          "NOTE: Candidate vessels are leads for investigation; this report does not establish responsibility."]
    return "\n".join(L) + "\n"
